[package]
name = "bloom-rs"
version = "0.1.0"
authors = ["vii <vii@gamecraft.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.1.2"
enum-utils = "0.1.2"
enum-display-derive = "0.1.1"
